"""tablas_iniciales

Revision ID: d424f44eb693
Revises: 
Create Date: 2026-06-20 02:51:04.509934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd424f44eb693'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_negocio', sa.String(length=200), nullable=False),
    sa.Column('correo_dedicado', sa.String(length=200), nullable=False),
    sa.Column('telegram_chat_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correos_notificacion', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('token_dashboard', sa.UUID(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo_dedicado'),
    sa.UniqueConstraint('token_dashboard')
    )
    op.create_table('pagos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('remitente', sa.String(length=200), nullable=False),
    sa.Column('banco_origen', sa.String(length=100), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_recibido', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email_raw', sa.Text(), nullable=True),
    sa.Column('notificado_telegram', sa.Boolean(), nullable=False),
    sa.Column('notificado_correo', sa.Boolean(), nullable=False),
    sa.Column('token_idempotencia', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_idempotencia')
    )
    op.create_table('logs_notificaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pago_id', sa.UUID(), nullable=False),
    sa.Column('canal', sa.String(length=50), nullable=False),
    sa.Column('destinatario', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs_notificaciones')
    op.drop_table('pagos')
    op.drop_table('clientes')
    # ### end Alembic commands ###
